nohup: ignoring input
Using Theano backend.
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
Traceback (most recent call last):
  File "cifar100_tr_baseline.py", line 63, in <module>
    model, layer_dict = CIFAR_arch.cifar10_100()
  File "/home/e91868xs/AIRepair/benchmarks/DeepCorrect/cifar_src/cifar_layer_arch.py", line 120, in cifar10_100
    model.add(BatchNormalization(mode=0, axis=1, trainable=set_trainable))
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/models.py", line 332, in add
    output_tensor = layer(self.outputs[0])
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/layers/normalization.py", line 91, in build
    name='{}_gamma'.format(self.name))
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/engine/topology.py", line 418, in add_weight
    weight = initializer(shape, name=name)
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/initializations.py", line 116, in one
    return K.ones(shape, name=name)
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 168, in ones
    return variable(np.ones(shape), dtype, name)
  File "/home/e91868xs/anaconda3/envs/theano/lib/python2.7/site-packages/numpy/core/numeric.py", line 190, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed
